export type Nullable<T> = T | null;
export type FailureState = "BLOCKED_DATA" | "BLOCKED_EVIDENCE" | "BLOCKED_AUTH" | "BLOCKED_EXECUTION" | "AMBIGUOUS_CHAIN";
export type TruthSource = "dexscreener" | "dexpaprika" | "geckoterminal" | "uniswap" | "rpc" | "okx" | "revert" | "vfat";
export type SourceTransport = "OFFICIAL_API" | "RPC" | "PUBLIC_ENDPOINT" | "DISCOVERED_ENDPOINT" | "HTML_DOM" | "BROWSER_DOM" | "NONE";
export type SourceStatus = { source:TruthSource; status:"READY"|"BLOCKED"; fetchedAt:string; failureState:Nullable<FailureState>; error:Nullable<string>; transport?:SourceTransport; url?:Nullable<string>; contentSha256?:Nullable<string>; blockNumber?:Nullable<string>; rpcUrl?:Nullable<string> };
export type SurfaceReceipt = { source:TruthSource; url:string; transport:SourceTransport; transportReady:boolean; status:"READY"|"BLOCKED"; addressMatched:boolean; structuredPayload:boolean; discoveredEndpoints:number; discoveredEndpointPaths:string[]; contentSha256:Nullable<string>; error:Nullable<string> };
export type SourceReceipt = { source:TruthSource; transport:Nullable<SourceTransport>; url:Nullable<string>; fetchedAt:string; status:"READY"|"BLOCKED"; failureState:Nullable<FailureState>; error:Nullable<string>; contentSha256:Nullable<string> };
export type TruthReceipt = { sourceUrl:Nullable<string>; transport:Nullable<SourceTransport>; asOf:Nullable<string>; contentSha256:Nullable<string>; blockNumber:Nullable<string>; rpcUrl:Nullable<string>; conflicts:string[]; failureState:Nullable<FailureState> };
export type PoolCandidate = { chainId:Nullable<string>; dexId:Nullable<string>; poolAddress:string; baseAddress:Nullable<string>; quoteAddress:Nullable<string>; baseSymbol:Nullable<string>; quoteSymbol:Nullable<string>; queriedTokenSide:Nullable<"base"|"quote">; priceUsd:Nullable<number>; volume24hUsd:Nullable<number>; liquidityUsd:Nullable<number>; feeTier:Nullable<number>; grossFee24hUsd:Nullable<number>; feeVelocity24h:Nullable<number>; capacityAdjustedFeeVelocity24h:Nullable<number>; poolAgeDays:Nullable<number>; source:string };
export type Ohlcv = { timestamp:number; open:number; high:number; low:number; close:number; volumeUsd:number };
export type OnchainPoolTruth = { chainId:string; poolAddress:string; factory:string; token0:string; token1:string; feeTier:number; tickSpacing:number; currentTick:number; sqrtPriceX96:string; activeLiquidityRaw:string; canonical:boolean };
export type TickLiquidityEvidence = { verified:boolean; source:"UNISWAP_V3_TICKLENS"; rpcUrl:Nullable<string>; tickLens:string; blockNumber:Nullable<string>; currentTick:number; tickSpacing:number; wordRadius:number; wordsQueried:number; initializedTickCount:number; nearestBelowTick:Nullable<number>; nearestAboveTick:Nullable<number>; nearestBelowDistance:Nullable<number>; nearestAboveDistance:Nullable<number>; totalLiquidityGrossRaw:string; top5GrossLiquidityConcentrationPct:Nullable<number>; error:Nullable<string> };
export type FeeGrowthEvidence = { verified:boolean; source:"UNISWAP_V3_POOL"; mode:Nullable<"ARCHIVE_WINDOW"|"LIVE_DELTA">; rpcUrl:Nullable<string>; requestedWindowSeconds:number; observedWindowSeconds:Nullable<number>; fromBlock:Nullable<string>; toBlock:Nullable<string>; fromTimestamp:Nullable<number>; toTimestamp:Nullable<number>; feeGrowthGlobal0X128DeltaRaw:Nullable<string>; feeGrowthGlobal1X128DeltaRaw:Nullable<string>; nonZeroGrowth:boolean; archiveReadVerified:boolean; error:Nullable<string> };
export type TruthArtifact = {
  schemaVersion:"lp-truth-v1";
  request:{tokenAddress:string};
  timestamp:string;
  selectedPool:Nullable<PoolCandidate>;
  poolCandidates:PoolCandidate[];
  verifiedPools:OnchainPoolTruth[];
  onchainPool:Nullable<OnchainPoolTruth>;
  poolSelection:{method:"VERIFIED_CAPACITY_ADJUSTED_FEE_VELOCITY"; verifiedCandidates:number; capacityLiquidityTargetUsd:number; feeBasis:"VOLUME_X_FEE_TIER_PROXY"};
  market:{ priceUsd:Nullable<number>; high24hUsd:Nullable<number>; low24hUsd:Nullable<number>; high7dUsd:Nullable<number>; low7dUsd:Nullable<number>; volume5mUsd:Nullable<number>; volume30mUsd:Nullable<number>; volume1hUsd:Nullable<number>; volume24hUsd:Nullable<number>; tvlUsd:Nullable<number>; activeLiquidityUsd:Nullable<number>; feeTier:Nullable<number>; poolAgeDays:Nullable<number>; tick:{current:Nullable<number>; lower:Nullable<number>; upper:Nullable<number>}; holderFlow:Nullable<{inflowUsd:number;outflowUsd:number}> };
  history:{ohlcv5m:Ohlcv[]; ohlcv30m:Ohlcv[]; ohlcv1h:Ohlcv[]; ohlcv1d:Ohlcv[]};
  onchainEvidence:{tickLiquidity:Nullable<TickLiquidityEvidence>; feeGrowth:Nullable<FeeGrowthEvidence>; directionalSwaps:null};
  evidence:{grade:"A"|"B"|"C"|"D"; freshnessSeconds:Nullable<number>; conflicts:string[]; wickPenalty:boolean; sources:SourceStatus[]; surfaceReceipts:SurfaceReceipt[]};
  receipts:{source:SourceReceipt[]; truth:TruthReceipt[]};
  failureState:Nullable<FailureState>;
};
